/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardScriptsRouteImport } from './routes/dashboard/scripts'
import { Route as DashboardResearchRouteImport } from './routes/dashboard/research'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard/library'
import { Route as DashboardFilmingRouteImport } from './routes/dashboard/filming'
import { Route as DashboardAddVideoRouteImport } from './routes/dashboard/add-video'
import { Route as DashboardVideosVideoIdRouteImport } from './routes/dashboard/videos/$videoId'
import { Route as DashboardScriptsScriptIdRouteImport } from './routes/dashboard/scripts/$scriptId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardScriptsRoute = DashboardScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardResearchRoute = DashboardResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFilmingRoute = DashboardFilmingRouteImport.update({
  id: '/filming',
  path: '/filming',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAddVideoRoute = DashboardAddVideoRouteImport.update({
  id: '/add-video',
  path: '/add-video',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVideosVideoIdRoute = DashboardVideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardScriptsScriptIdRoute =
  DashboardScriptsScriptIdRouteImport.update({
    id: '/$scriptId',
    path: '/$scriptId',
    getParentRoute: () => DashboardScriptsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/add-video': typeof DashboardAddVideoRoute
  '/dashboard/filming': typeof DashboardFilmingRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/research': typeof DashboardResearchRoute
  '/dashboard/scripts': typeof DashboardScriptsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/scripts/$scriptId': typeof DashboardScriptsScriptIdRoute
  '/dashboard/videos/$videoId': typeof DashboardVideosVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/add-video': typeof DashboardAddVideoRoute
  '/dashboard/filming': typeof DashboardFilmingRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/research': typeof DashboardResearchRoute
  '/dashboard/scripts': typeof DashboardScriptsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/scripts/$scriptId': typeof DashboardScriptsScriptIdRoute
  '/dashboard/videos/$videoId': typeof DashboardVideosVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/add-video': typeof DashboardAddVideoRoute
  '/dashboard/filming': typeof DashboardFilmingRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/research': typeof DashboardResearchRoute
  '/dashboard/scripts': typeof DashboardScriptsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/scripts/$scriptId': typeof DashboardScriptsScriptIdRoute
  '/dashboard/videos/$videoId': typeof DashboardVideosVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/add-video'
    | '/dashboard/filming'
    | '/dashboard/library'
    | '/dashboard/research'
    | '/dashboard/scripts'
    | '/dashboard/'
    | '/dashboard/scripts/$scriptId'
    | '/dashboard/videos/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/add-video'
    | '/dashboard/filming'
    | '/dashboard/library'
    | '/dashboard/research'
    | '/dashboard/scripts'
    | '/dashboard'
    | '/dashboard/scripts/$scriptId'
    | '/dashboard/videos/$videoId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/add-video'
    | '/dashboard/filming'
    | '/dashboard/library'
    | '/dashboard/research'
    | '/dashboard/scripts'
    | '/dashboard/'
    | '/dashboard/scripts/$scriptId'
    | '/dashboard/videos/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/scripts': {
      id: '/dashboard/scripts'
      path: '/scripts'
      fullPath: '/dashboard/scripts'
      preLoaderRoute: typeof DashboardScriptsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/research': {
      id: '/dashboard/research'
      path: '/research'
      fullPath: '/dashboard/research'
      preLoaderRoute: typeof DashboardResearchRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/filming': {
      id: '/dashboard/filming'
      path: '/filming'
      fullPath: '/dashboard/filming'
      preLoaderRoute: typeof DashboardFilmingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/add-video': {
      id: '/dashboard/add-video'
      path: '/add-video'
      fullPath: '/dashboard/add-video'
      preLoaderRoute: typeof DashboardAddVideoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/videos/$videoId': {
      id: '/dashboard/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/dashboard/videos/$videoId'
      preLoaderRoute: typeof DashboardVideosVideoIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/scripts/$scriptId': {
      id: '/dashboard/scripts/$scriptId'
      path: '/$scriptId'
      fullPath: '/dashboard/scripts/$scriptId'
      preLoaderRoute: typeof DashboardScriptsScriptIdRouteImport
      parentRoute: typeof DashboardScriptsRoute
    }
  }
}

interface DashboardScriptsRouteChildren {
  DashboardScriptsScriptIdRoute: typeof DashboardScriptsScriptIdRoute
}

const DashboardScriptsRouteChildren: DashboardScriptsRouteChildren = {
  DashboardScriptsScriptIdRoute: DashboardScriptsScriptIdRoute,
}

const DashboardScriptsRouteWithChildren =
  DashboardScriptsRoute._addFileChildren(DashboardScriptsRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAddVideoRoute: typeof DashboardAddVideoRoute
  DashboardFilmingRoute: typeof DashboardFilmingRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardResearchRoute: typeof DashboardResearchRoute
  DashboardScriptsRoute: typeof DashboardScriptsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardVideosVideoIdRoute: typeof DashboardVideosVideoIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAddVideoRoute: DashboardAddVideoRoute,
  DashboardFilmingRoute: DashboardFilmingRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardResearchRoute: DashboardResearchRoute,
  DashboardScriptsRoute: DashboardScriptsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardVideosVideoIdRoute: DashboardVideosVideoIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
